### ISSUE TITLE
提示"token无效,请重新登录"

### ISSUE THREAD

**Issue by hsf1002** [LiangLuDev/WeYueReader#16]
E/RxHttpUtils: <-- 200 OK http://www.luliangdev.cn/api/books?type=reputation&major=%E5%A5%87%E5%B9%BB&page=1 (107ms)
E/RxHttpUtils: X-Powered-By: Express
E/RxHttpUtils: Content-Type: application/json; charset=utf-8
E/RxHttpUtils: Content-Length: 50
E/RxHttpUtils: ETag: W/"32-dC39mPO+dUAuYips7ZO0vcDfdCM"
E/RxHttpUtils: Date: Tue, 15 May 2018 06:52:22 GMT
E/RxHttpUtils: Connection: keep-alive
E/RxHttpUtils: {"code":60002,"msg":"token无效,请重新登录"}

**Comment by LiangLuDev** [comment]
@hsf1002 需要登录才可以
