### ISSUE TITLE
请求超时，请问服务器没有维护了吗

### ISSUE THREAD

**Issue by twopai** [LiangLuDev/WeYueReader#21]
08-01 10:06:57.801 22967-24906/com.lianglu.weyue E/RxHttpUtils: --> GET http://192.168.5.87:3389/api/classify http/1.1
08-01 10:06:57.801 22967-24809/com.lianglu.weyue E/RxHttpUtils: app-type: Android
08-01 10:06:57.801 22967-24908/com.lianglu.weyue E/RxHttpUtils: app-type: Android
08-01 10:06:57.801 22967-24906/com.lianglu.weyue E/RxHttpUtils: app-type: Android
08-01 10:06:57.801 22967-24809/com.lianglu.weyue E/RxHttpUtils: access-token: weyue
08-01 10:06:57.801 22967-24908/com.lianglu.weyue E/RxHttpUtils: access-token: weyue
08-01 10:06:57.801 22967-24906/com.lianglu.weyue E/RxHttpUtils: access-token: weyue
08-01 10:06:57.801 22967-24809/com.lianglu.weyue E/RxHttpUtils: --> END GET
08-01 10:06:57.801 22967-24908/com.lianglu.weyue E/RxHttpUtils: --> END GET
08-01 10:06:57.801 22967-24906/com.lianglu.weyue E/RxHttpUtils: --> END GET
08-01 10:07:07.666 22967-24907/com.lianglu.weyue E/RxHttpUtils: <-- HTTP FAILED: java.net.SocketTimeoutException: connect timed out

**Comment by LiangLuDev** [comment]
@twopai 请查看常见问题。

**Comment by twopai** [comment]
可以了谢谢
